language: c++
script: CFLAGS=-Wall ./configure && make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}') && make test
dist: bionic
before_install:
  - git submodule update --init --recursive 
  - sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
  - sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libwebp-dev libpoco-dev libncurses-dev
addons:
  apt:
    update: true