name: Release

on:
  release:
    types: [published]

jobs:
  reddit:
    runs-on: ubuntu-latest
    steps:
    - uses: BjornLuG/release-for-reddit-action@v1
      with:
        username: ${{ secrets.REDDIT_USERNAME }}
        password: ${{ secrets.REDDIT_PASSWORD }}
        app-id: ${{ secrets.REDDIT_APP_ID }}
        app-secret: ${{ secrets.REDDIT_APP_SECRET }}
        subreddit: craftos_pc
        title: CraftOS-PC ${{ github.event.release.tag_name }} is now available!
        comment: ${{ github.event.release.body }}
        flair-id: 33b418d2-8e71-11ea-b7d8-0e1aee799c6b
